# Generated by Django 2.2.5 on 2020-10-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movielist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=20)),
                ('movie_url', models.CharField(max_length=15)),
                ('movie_pic', models.CharField(max_length=15)),
                ('star_num', models.CharField(max_length=15)),
            ],
        ),
    ]
