# Generated by Django 2.2.5 on 2020-10-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_page', '0002_movielist_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='movie_pic',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='movie_url',
            field=models.CharField(max_length=55),
        ),
    ]
