# Generated by Django 2.2.5 on 2020-10-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_page', '0003_auto_20201011_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='movie_url',
            field=models.CharField(max_length=100),
        ),
    ]
