# Generated by Django 2.2.5 on 2020-10-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_page', '0005_auto_20201012_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='view_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='year',
            field=models.IntegerField(),
        ),
    ]
