# Generated by Django 2.2.5 on 2020-10-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_page', '0006_auto_20201014_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='desc',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
