# Generated by Django 2.2.5 on 2020-10-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_page', '0007_movielist_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrage_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Barrage_content', models.CharField(max_length=20)),
                ('movie_id', models.CharField(max_length=100)),
            ],
        ),
    ]
