# Generated by Django 2.2.5 on 2020-10-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_page', '0008_barrage_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barrage_list',
            name='Barrage_content',
        ),
        migrations.AddField(
            model_name='barrage_list',
            name='author_tmp',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barrage_list',
            name='color_tmp',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barrage_list',
            name='text_tmp',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barrage_list',
            name='time_tmp',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barrage_list',
            name='type_tmp',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
